### ISSUE TITLE
Launch Issue

### ISSUE THREAD

**Issue by atulpimple4** [Stormower/NecroBotInstanceCreator#1]
After Launch Necro flashes all over and then nothing.. Created 150+ bat files after adding 10 accounts..

**Comment by defaultbr** [comment]
I guess you selected the wrong config file, i was doing the same thing but selecting the Config.json, you must SELECT the config.TXT (look the .txt at the end) that is created after clicking in "Create", and select the .txt and click in launch....  hope it help
